name: "Bug report"
description: "File a bug report"
labels: ["type: bug"]
body:
  - type: "checkboxes"
    id: "latest-version"
    attributes:
      label: "Does this bug affect {{ project_version }} of {{ project_name }}?"
      description: "Before reporting, `pip install {{ project_name }}=={{ project_version }}` and verify the issue is still present."
      options:
        - label: "This bug affects {{ project_version }} of {{ project_name }}."
          required: true
  - type: "checkboxes"
    id: "no-duplicate-issues"
    attributes:
      label: "Please check that this issue hasn't been reported before."
      description: "The **Label filters** may help make your search more focussed."
      options:
        - label: "I searched previous [Bug Reports](https://github.com/{{ project_owner_github_username }}/{{ github_repo_name }}/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+bug%22+sort%3Acomments-desc) and didn't find any similar reports."
          required: true
  - type: "textarea"
    id: "expected"
    attributes:
      label: "Expected Behavior"
      description: "Tell us what **should** happen."
    validations:
      required: true
  - type: "textarea"
    id: "what-happened"
    attributes:
      label: "Current behaviour"
      description: "Tell us what happens instead of the expected behavior."
    validations:
      required: true
  - type: "textarea"
    id: "reproduce"
    attributes:
      label: "Steps to reproduce"
      description: "Which exact steps can a developer take to reproduce the issue? The more detail you provide, the easier it will be to narrow down and fix the bug."
    validations:
      required: true
  - type: "checkboxes"
    id: "operating-systems"
    attributes:
      label: "Which operating system(s) are you using?"
      description: "You may select more than one."
      options:
        - label: "Linux"
        - label: "macOS"
        - label: "Windows"
  - type: "input"
    id: "version"
    attributes:
      label: "Version"
      description: Which `{{ project_name }}` version are you using? You may be able to obtain this information by running `pip show {{ project_name }}` in your terminal.
      placeholder: "0.0.0"
    validations:
      required: true
  - type: "textarea"
    id: "possible-solution"
    attributes:
      label: "Possible solution"
      description: "Please suggest a fix or reason for the bug, if you have an idea."
